from pygame import Vector2

#Pixel Scaling
PIXEL_REDUCTION_FACTOR = 3

#Colours
BACKGROUND_COLOUR = (0, 18, 25)
TRACK_BARRIER_COLOUR = (148, 210, 189)

#Board Variables
VANISHING_POINT_POSITION = Vector2(0.5, 0.6)
TRACK_CENTRE_POSITION = Vector2(0.5, 1)
TRACKS_MAX_WIDTH = 0.7
TRACK_MAX_WIDTH = 0.2

#Track VFX Variables
TRACK_VFX_LENGTH = 0.6
TRACK_VFX_NUM_POINTS = 50
TRACK_VFX_SPRING_CONSTANT = 0.005
TRACK_VFX_SPRING_CONSTANT_BASELINE = 1
TRACK_VFX_DAMPING = 0.98
TRACK_VFX_ITERATIONS = 5
TRACK_VFX_PRESS_STRENGTH = 0.01
TRACK_VFX_MAX_STRAY = 0.05

